apiVersion: apps/v1
kind: Deployment
metadata:
 name: jo-app-api-deployment
 labels:
   app: jo-app-api
spec:
 replicas: 2
 selector:
   matchLabels:
     app: jo-app-api
 template:
   metadata:
     labels:
       app: jo-app-api
   spec:
     serviceAccountName: mobio
     containers:
       - name: jo
         image: {image}
         imagePullPolicy: IfNotPresent
         command: ["/bin/sh", "-c"]
         args: ["cd $JO_HOME; sh prepare_env.sh && uwsgi --http :80 --wsgi-file app_jo_api.py --callable app --master --processes 4 -b 65536 --lazy --enable-threads"]
         envFrom:
           - configMapRef:
               name: mobio-config
           - secretRef:
               name: mobio-secret
         ports:
           - containerPort: 80
         resources:
           requests:
             memory: 70Mi
             cpu: 80m
           limits:
             memory: 1Gi
             cpu: 800m
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
         livenessProbe:
           httpGet:
             port: 80
             path: /api/v1.0/ping
           initialDelaySeconds: 120
           periodSeconds: 5
           timeoutSeconds: 4
           successThreshold: 1
           failureThreshold: 3
     initContainers:
       - name: init-jo
         image: {image}
         command: [ '/bin/sh', '-c', "cd $JO_HOME; sh prepare_env.sh && sh check_image.sh" ]
         envFrom:
           - configMapRef:
               name: mobio-config
           - secretRef:
               name: mobio-secret
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
           - name: mobio-public-shared-data
             mountPath: /media/data/public_resources/
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: jo-app-api-service
 labels:
   app: jo-app-api
spec:
 ports:
   - port: 80
 selector:
   app: jo-app-api
